### ISSUE TITLE
candyコマンドのシェバングが `/usr/local/opt/python/bin/python2.7` になっている

### ISSUE THREAD

**Issue by ghost** [CANDY-LINE/candy-board-cli#1]
```
#!/usr/local/opt/python/bin/python2.7
```

になっています。
リポジトリのファイル等は`/usr/bin/env python`ですが、pypiにアップロードされているwhlファイルに含まれる`candy`がそのようになっていました。
https://pypi.python.org/pypi/candy-board-cli/1.0.3

**Comment by dbaba** [comment]
お使いの環境に合わせてインストールするために、以下のようにインストール時に実行環境をご指定いただけますでしょうか。

```
pip install --upgrade candy-board-cli \
    --global-option=build \
    --global-option="--executable=$(which python)"
```

**Comment by ghost** [comment]
https://github.com/CANDY-LINE/LTEPi2-info/blob/master/インストール方法.md
こちらの手順に従い、

```
$ curl -L https://git.io/vKyOf | sudo CANDY_RED=0 bash
```

を、raspbian上で実行したところ、インストールされたcandyコマンドのシェバングが上記のようになっておりましたので、お知らせしました。

**Comment by dbaba** [comment]
ありがとうございます。
本モジュールをPyPiへpublishする時に、setuptoolsがshebangを強制的に変更するという動作は認識しております。
このため、本モジュールをインストールする場合には、スクリプト内にてpipの引数に動作環境を指定し、インストール先の環境に合わせてshebangが変更されるようにしています。

**Comment by ghost** [comment]
私は、LTEPi for Dを使用する際、ドキュメントに書かれた手順でインストールしましたが、動作しなかったので報告した次第です。
動作しなかった原因は上記の通りで、install.shを実行した環境に`/usr/local/opt/python/bin/python2.7`がないからです。

> このため、本モジュールをインストールする場合には、スクリプト内にてpipの引数に動作環境を指定し、インストール先の環境に合わせてshebangが変更されるようにしています。

意図されている変更が行われていないのではないかと思いますが、問題ないとの認識であれば閉じていただければ。

**Comment by dbaba** [comment]
ご報告いただきありがとうございます。
こちらで確認している状況と異なりますので、何か別の要因があるかもしれません。

インストールを行われた時期は、15日以上前でしょうか？それとも最近行われましたか？
以前は、ご報告いいただいた内容が発生する可能性がありましたので確認しております。

また、可能であれば、アンインストールののち、再度インストールを行っていただけますでしょうか。以下のようにCANDY_RED=0としていただければ、処理時間は長くはありません。

```
sudo /opt/candy-line/ltepi2/uninstall.sh
sudo reboot
(再起動後)
curl -L https://git.io/vKyOf | sudo CANDY_RED=0 bash
```

**Comment by ghost** [comment]
実行したのはこのissueの作成日です。

**Comment by dbaba** [comment]
ありがとうございます。そうしますと、環境においてなんらかの違いがあるのかもしれません。

私にて動作を確認した環境は以下の通りです。

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l GNU/Linux
pi@raspberrypi:~ $ python --version
Python 2.7.9
pi@raspberrypi:~ $ pip --version
heapip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
pi@raspberrypi:~ $ head -1 /usr/local/bin/candy
#!/usr/bin/python
```

同様のコマンドで環境を教えていただけますか？また、再度入れ直した結果（[こちらの方法](https://github.com/CANDY-LINE/candy-board-cli/issues/1#issuecomment-252390993)）も同じように書き換わっていない状況でしょうか？

**Comment by ghost** [comment]
```
$ curl -L https://git.io/vKyOf | sudo CANDY_RED=0 bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4558  100  4558    0     0   2458      0  0:00:01  0:00:01 --:--:-- 10904
Downloading/unpacking candy-board-cli
  Downloading candy_board_cli-1.0.3-py2-none-any.whl
Installing collected packages: candy-board-cli
Successfully installed candy-board-cli
Cleaning up...
Downloading/unpacking candy-board-amt
  Downloading candy_board_amt-1.2.0-py2-none-any.whl
Installing collected packages: candy-board-amt
Successfully installed candy-board-amt
Cleaning up...
[INFO] Installing system service ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132    0   132    0     0    154      0 --:--:-- --:--:-- --:--:--   154
100 10905    0 10905    0     0   6548      0 --:--:--  0:00:01 --:--:-- 50022
Created symlink from /etc/systemd/system/multi-user.target.wants/ltepi2.service to /lib/systemd/system/ltepi2.service.
[INFO] ltepi2 service has been installed
[ALERT] *** Please reboot the system (enter 'sudo reboot') ***
pi@raspberrypi:~ $ head -1 /usr/local/bin/candy 
#!/usr/local/opt/python/bin/python2.7
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux
pi@raspberrypi:~ $ python -V
Python 2.7.9
pi@raspberrypi:~ $ pip -V
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
```

**Comment by ghost** [comment]
お試しになっている環境では、pipが`/usr/local/lib/`以下を指しているようですが、`/usr/local`以下にPython環境があるのでしょうか。
明示的に導入していない限りは`/usr/`で、`/usr/local`にはないと思います。
pipインストール時に、そのパスにpythonがないと、書き換えは行われないのではないでしょうか。
素のRaspbian環境で実行していただくと、再現するかもしれませんね。

**Comment by ghost** [comment]
あと、pipインストール時にexecutableを指定しないといけない、というのはPythonパッケージとしては使いにくいと思います。
candyスクリプトを拝見すると、sdistだけで良さそうに思いますがいかがでしょうか。
bdist_wheelを残されるのであれば、publishを実行される際に、OS標準のpythonを使用されることで回避できるのではないでしょうか。

**Comment by dbaba** [comment]
ありがとうございます。pipのバージョンに違いがありますね。最新のpipと挙動が異なるようです。
これは、こちらのスクリプトあるいはご案内のミスとなります。ご不便をおかけして申し訳ございません。

また、ご指摘の件情報ありがとうございます。早速こちらで試してみて、うまくいくようであれば更新いたします。

また、当座の対応としては、pipをアップグレードしていただくようご案内いたします。

**Comment by dbaba** [comment]
bidst_wheelをpublishしていたスクリプトを修正し、candyスクリプトがRaspbianで動作することを確認できました。

```
pi@raspberrypi:~ $ sudo pip install candy-board-cli --no-cache-dir
Collecting candy-board-cli
  Downloading candy-board-cli-1.0.5.tar.gz
Installing collected packages: candy-board-cli
  Running setup.py install for candy-board-cli ... done
Successfully installed candy-board-cli-1.0.5
pi@raspberrypi:~ $ head -1 /usr/local/bin/candy
#!/usr/bin/python
pi@raspberrypi:~ $ candy ls
usage: candy [-h] {version,apn,network,sim,modem,service} ...
candy: error: argument category: invalid choice: 'ls' (choose from 'version', 'apn', 'network', 'sim', 'modem', 'service')
```

ご協力ありがとうございました！

**Comment by ghost** [comment]
私の方でも確認しました。
ご対応ありがとうございました。
